spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id:  testgroup
      bootstrap-servers:
      - localhost:9095
    producer:
      bootstrap-servers:
      - localhost:9095
    